[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "numpy>=2.5.3",
    "opencv-python-headless>=5.0.0.93",
    "pillow>=12.3.0",
    "pytest>=9.1.1",
    "python-multipart>=0.0.32",
    "ultralytics>=8.4.165",
    "uvicorn>=0.54.0",
]
